spring.application.name: mos-microservice

feign:
  client:
    config:
      default:
        readTimeout: 2000



resilience4j:
  circuitbreaker:
    instances:
      testBreaker:
        failureRateThreshold: 20
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
      vaccinationService:
        failureRateThreshold: 20
        minimumNumberOfCalls: 5
        slidingWindowSize: 100
        slidingWindowType: COUNT_BASED
        waitDurationInOpenState: 10s
